[CBRD-25316] For UPDATE JOIN statements, aggregate functions or analytic functions cannot be used in the SET and WHERE clauses
http://jira.cubrid.org/browse/CBRD-25316

Changes to the answers as follows:
1. Do not allow the use of analytic functions in the SET and WHERE clauses of UPDATE JOIN statements.

For example:
```
update /*+ recompile */
  t1 a, t2 b
set
  a.c_r_nl = avg (b.c2) over (partition by b.c1)
where
  a.c1 = b.c1;

-- AS-IS
3 rows affected.

-- TO-BE
ERROR: before '  where a.c1 = b.c1; '
Nested analytic functions are not allowed.
```